import React from "react";
export function filterData(searchText, restaurants) {
  const resFilterData = restaurants.filter((restaurant) =>
    restaurant?.info?.name.toLowerCase().includes(searchText.toLowerCase())
  );
  return resFilterData;
}
var nameList = [
  "Time",
  "Past",
  "Future",
  "Dev",
  "Fly",
  "Flying",
  "Soar",
  "Soaring",
  "Power",
  "Falling",
  "Fall",
  "Jump",
  "Cliff",
  "Mountain",
  "Rend",
  "Red",
  "Blue",
  "Green",
  "Yellow",
  "Gold",
  "Demon",
  "Demonic",
  "Panda",
  "Cat",
  "Kitty",
  "Kitten",
  "Zero",
  "Memory",
  "Trooper",
  "XX",
  "Bandit",
  "Fear",
  "Light",
  "Glow",
  "Tread",
  "Deep",
  "Deeper",
  "Deepest",
  "Mine",
  "Your",
  "Worst",
  "Enemy",
  "Hostile",
  "Force",
  "Video",
  "Game",
  "Donkey",
  "Mule",
  "Colt",
  "Cult",
  "Cultist",
  "Magnum",
  "Gun",
  "Assault",
  "Recon",
  "Trap",
  "Trapper",
  "Redeem",
  "Code",
  "Script",
  "Writer",
  "Near",
  "Close",
  "Open",
  "Cube",
  "Circle",
  "Geo",
  "Genome",
  "Germ",
  "Spaz",
  "Shot",
  "Echo",
  "Beta",
  "Alpha",
  "Gamma",
  "Omega",
  "Seal",
  "Squid",
  "Money",
  "Cash",
  "Lord",
  "King",
  "Duke",
  "Rest",
  "Fire",
  "Flame",
  "Morrow",
  "Break",
  "Breaker",
  "Numb",
  "Ice",
  "Cold",
  "Rotten",
  "Sick",
  "Sickly",
  "Janitor",
  "Camel",
  "Rooster",
  "Sand",
  "Desert",
  "Dessert",
  "Hurdle",
  "Racer",
  "Eraser",
  "Erase",
  "Big",
  "Small",
  "Short",
  "Tall",
  "Sith",
  "Bounty",
  "Hunter",
  "Cracked",
  "Broken",
  "Sad",
  "Happy",
  "Joy",
  "Joyful",
  "Crimson",
  "Destiny",
  "Deceit",
  "Lies",
  "Lie",
  "Honest",
  "Destined",
  "Bloxxer",
  "Hawk",
  "Eagle",
  "Hawker",
  "Walker",
  "Zombie",
  "Sarge",
  "Capt",
  "Captain",
  "Punch",
  "One",
  "Two",
  "Uno",
  "Slice",
  "Slash",
  "Melt",
  "Melted",
  "Melting",
  "Fell",
  "Wolf",
  "Hound",
  "Legacy",
  "Sharp",
  "Dead",
  "Mew",
  "Chuckle",
  "Bubba",
  "Bubble",
  "Sandwich",
  "Smasher",
  "Extreme",
  "Multi",
  "Universe",
  "Ultimate",
  "Death",
  "Ready",
  "Monkey",
  "Elevator",
  "Wrench",
  "Grease",
  "Head",
  "Theme",
  "Grand",
  "Cool",
  "Kid",
  "Boy",
  "Girl",
  "Vortex",
  "Paradox",
];
const Messages = [
  "Hey everyone, welcome to the live stream! ",
  "So excited to be live with you guys today! ",
  "Who's tuning in from [specific location]?",
  "Let me know what questions you have about [topic] in the chat!",
  "Don't forget to hit that subscribe button and ring the notification bell!",

  "Just dropped my coffee... live stream chaos begins! ☕️",
  "If I can do this live, you can definitely [achieve something related to your video]! ",
  "Send me your funniest pet memes in the chat, I need a laugh! ",
  "Let's play a quick poll in the chat: [insert two funny options related to your video]?",
  "Can anyone relate to [funny/awkward situation related to your topic]?",

  "Did you know [interesting fact about your topic]?",
  "Let's dive into the biggest misconception about [topic]. ",
  "Here are 3 actionable tips you can use right now [related to your video].",
  "What are your biggest challenges with [topic]? Share them in the comments!",
  "I'm passionate about [aspect of your topic]. Why is it important to you?",
  "Share this live stream with your friends who are interested in [topic]! ",
  "Follow me on Instagram for more behind-the-scenes content! @yourusername",
  "Let's build a community around [topic]. Tag your friends who would love this!",
  "Remember to leave a comment and let me know what you thought of the live stream! ",
  "I'm doing a giveaway at the end of the stream! Make sure you stick around! ",
];

export function generate() {
  var finalName = nameList[Math.floor(Math.random() * nameList.length)];
  return finalName;
}
export function generatemessgae() {
  var finalName = Messages[Math.floor(Math.random() * Messages.length)];
  return finalName;
}
